import_espi_xml:
  fields:
    xml:
      required: true
      example: "<feed>...</feed>"
      selector:
        text:
          multiline: true

delete_statistics:
  fields:
    statistic_id:
      required: true
      example: "green_button:home_energy_consumption"
      selector:
        text:

log_statistics:
  target:
    entity:
      domain: number
      integration: green_button
  fields:
    start:
      required: true
      selector:
        datetime:
    end:
      required: true
      selector:
        datetime:

reset:
  target:
    entity:
      domain: number
      integration: green_button
